### ISSUE TITLE
Implement `doc_freq` on Searcher

### ISSUE THREAD

**Issue by I8dNLo** [quickwit-oss/tantivy-py#344]
Hi! Is there any way to get tf-idf representations for my databases? I want to check out the resulting vectors and use them at the next steps of my recommender pipeline

Are there any way to get them with python?

**Comment by cjrh** [comment]
Hi @I8dNLo 

No there is no such feature currently.

I saw that you asked the same question on the upstream tantivy repo here: https://github.com/quickwit-oss/tantivy/issues/2487.  That was the right place to ask the question, because here at tantivy-py we aim only to wrap the underlying tantivy library and avoid adding additional features.

I did also find a similar question with some discussion, again at upstream, here: https://github.com/quickwit-oss/tantivy/issues/341.

I don't think there is much we can do here to resolve your issue so I'm going to close this issue. But if I'm wrong please let me know and I'll open it again.

**Comment by I8dNLo** [comment]
Hm, I just see useful instruments in [here](https://docs.rs/tantivy/latest/src/tantivy/core/searcher.rs.html#132), but no bindings into python package. It's no problem to count term_freq for a given doc, but df is computed on a base level. It could be also in handy to return stemmed doc back for examinationю

**Comment by cjrh** [comment]
Ok, we can certainly include `doc_freq`.  Is there a way to return the stemmed doc in upstream tantivy?

**Comment by cjrh** [comment]
I made #345 to add `doc_freq` to the Searcher.
