### ISSUE TITLE
Adding boost/weight to fields

### ISSUE THREAD

**Issue by AliFlux** [quickwit-oss/tantivy-py#50]
Hi,

Is there a way to add custom weight score to a specific field in tantivy-py. For example if our schema has both `title` and `description` fields. And we want the item that matches title to prioritize in the list, we can add weight to title

In whoosh, we can achieve this via `field_boost`:

```py
title = whoosh.fields.TEXT(stored=True, field_boost=5.0)
description = whoosh.fields.TEXT(stored=True)
```

Tantivy natively supports boosting:
https://github.com/quickwit-oss/tantivy/blob/db1836691ef9b4f963070bfd9ef13c6d44d2a074/src/query/query_parser/query_parser.rs#L164
https://docs.rs/tantivy/0.16.0/tantivy/query/struct.QueryParser.html#method.set_field_boost

**Comment by VsevolodZakharov** [comment]
At least 
index.parse_query("title:t^2 OR content:i^3") 
gives repr
Query(BooleanQuery { subqueries: [(Should, Boost(query=TermQuery(Term(field=1,bytes=[116])), boost=2)), (Should, Boost(query=TermQuery(Term(field=2,bytes=[105])), boost=3))] })

But construction queries from Query classes is missing in tantivy-py. That wokrs fine in Whoosh. Otherwise parse_query should support fuzzy search, wildcards etc.

**Comment by VsevolodZakharov** [comment]
@AliFlux AFAIK No, it is not available.

**Comment by fulmicoton** [comment]
It exists in tantivy:
https://docs.rs/tantivy/latest/tantivy/query/struct.QueryParser.html#method.set_field_boost

Someone just needs to plug it.
